CREATE TABLE subscriptions (
id INT AUTO_INCREMENT PRIMARY KEY,
ad_link VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
user_confirmed TINYINT(1) DEFAULT 0,
token VARCHAR(32) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
